// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntqmgfjceiriumtcilhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cW1nZmpjZWlyaXVtdGNpbGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjMzODEsImV4cCI6MjA3MzA5OTM4MX0.H7yg9F9SLmlEC7zMyYWPhJ-2IGldQwkW00vU3x3Rocs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});